set_property PACKAGE_PIN B11 [get_ports can_signal_in]
set_property PACKAGE_PIN G13 [get_ports to_dominant]
set_property PACKAGE_PIN A11 [get_ports to_recessive]
set_property PACKAGE_PIN D12 [get_ports triger]
set_property IOSTANDARD LVCMOS33 [get_ports can_signal_in]
set_property IOSTANDARD LVCMOS33 [get_ports to_dominant]
set_property IOSTANDARD LVCMOS33 [get_ports to_recessive]
set_property IOSTANDARD LVCMOS33 [get_ports triger]
set_property PACKAGE_PIN A8 [get_ports switch_0]
set_property IOSTANDARD LVCMOS33 [get_ports switch_0]

set_property PACKAGE_PIN D13 [get_ports debug]
set_property PACKAGE_PIN B18 [get_ports debug_1]
set_property PACKAGE_PIN A18 [get_ports debug_2]
set_property IOSTANDARD LVCMOS33 [get_ports debug]
set_property IOSTANDARD LVCMOS33 [get_ports debug_1]
set_property IOSTANDARD LVCMOS33 [get_ports debug_2]

set_property PACKAGE_PIN D9 [get_ports BTN_0]
set_property PACKAGE_PIN C9 [get_ports BTN_1]
set_property PACKAGE_PIN B9 [get_ports BTN_2]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_0]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_1]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_2]
